[package]
name = "json_binary_tree_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1.0.11", features = ["derive"] }
serde_json = "1.0.2"
rand = "0.8.5"